### ISSUE TITLE
Highlight modified/new files in fuzzy-finder

### ISSUE THREAD

**Issue by andreiucm** [karabaja4/vscode-explorer-git-status#2]
Sometimes it necessary to hide the source-tree  to work with free-distraction. Or just for the comfort. 
So if we open the fuzzy finder to search some files will be very helpful if the modified/new files also will be highlighted. So it will be easy to figure out where the work is done.
I think the community don ask for this kind of feature yet so it will be a step forward :)

**Comment by karabaja4** [comment]
Sorry, this seems out of scope of this project since the finder in Code has an entirely different html markup which would mean considerable amount of code added to this script, as well as double amount of CSS classes injected to the global markup (one for finder, one for solution tree). Since the logic is already super hacky, I am reluctant to complicate it further.
