### ISSUE TITLE
Search for files

### ISSUE THREAD

**Issue by ost-ing** [karabaja4/vscode-explorer-git-status#9]
Hey,

Thank you for this.
After installation I found that although the file explorer correctly highlighted files that are apart of git, that the search and also open file shortcut (Command+P for macOS) did not reduce the results to what is committed to git..
Is this intended? If not, perhaps its a feature that could be considered?

Kind regards

**Comment by karabaja4** [comment]
Hello,

this has already been requested in #2, however as explained there I have no plans to add any additional features to this script since it would mean over-hacking VS Code. I'm sure VS Code developers will eventually adopt these features and properly implement git status, which will render this script obsolete. Sorry.

Regards,

Igor
